export const API_BASE_URL = "http://localhost:8000";
export const QUESTIONS_ARRAY = [
  "¿Tiene alergía a algun/os de los siguientes medicamentos?",
  "¿Tiene alergía a algun/os de los siguientes alimentos?",
  "¿Presenta algun/os de los siguientes síntomas?",
  "¿Presenta problemas en algun/os de los 5 sentidos?",
  "¿Presenta inflamación en algun/as de las siguientes partes de su cuerpo?",
  "¿Presenta manchas en algun/as de las siguientes partes de su cuerpo?",
  "¿Presenta comezón en algun/as de las siguientes partes de su cuerpo?",
  "¿Siente algun/os de los siguientes tipos de dolor?",
  "¿Hace cuánto experimenta los síntomas?",
  "¿Con qué frecuencia experimenta los síntomas?",
  "¿Cuál/es de los siguientes medicamentos consume?",
  "¿Ha tenido contacto con algún enfermo?",
  "¿Qué diagnóstico tenía el enfermo?",
  "¿Tenía síntomas relacionados a los suyos?",
  "¿Ha tenido contacto con algún agente infeccioso o tóxico?",
  "¿De qué tipo era dicho agente?",
  "¿Ha viajado al extranjero recientemente?",
  "¿A qué país/es viajó?",
  "¿Cómo define su estado de ánimo? Especifique decaido, cansado, ansioso, normal, falta de apetito, etc.",
];
export const OPTIONS_ARRAY = [
  [
    "Penicilina",
    "Sulfonamidas",
    "Aspirina",
    "Anestésicos",
    "Cefalosporiinas",
    "Antiinflamatorios",
    "Insulina",
    "Ninguno",
    "Otros",
  ],
  [
    "Frutos secos",
    "Mariscos",
    "Lácteos",
    "Huevos",
    "Trigo",
    "Frutas o verduras",
    "Soja",
    "Gluten",
    "Ninguno",
    "Otros",
  ],
  [
    "Fiebre",
    "Tos",
    "Dificultad respiratorio",
    "Pérdida del conocimiento",
    "Alteración del sueño",
    "Fatiga",
    "Ninguna",
  ],
  ["Audición", "Gusto", "Olfato", "Tacto", "Vista"],
  [
    "Cabeza",
    "Extremidades superiores",
    "Extremidades inferiores",
    "Amígdalas",
    "Aparato reproductor",
    "Abdomen",
    "Ninguno",
    "Otros",
  ],
  [
    "Cabeza",
    "Extremidades superiores",
    "Extremidades inferiores",
    "Cuello",
    "Espalda",
    "Aparato reproductor",
    "Abdomen",
    "Ninguno",
    "Otros",
  ],
  [
    "Cabeza",
    "Extremidades superiores",
    "Extremidades inferiores",
    "Cuello",
    "Espalda",
    "Aparato reproductor",
    "Abdomen",
    "Ninguno",
    "Otros",
  ],
  [
    "Dolor de cabeza",
    "Dolor en extremidades",
    "Dolor muscular",
    "Dolor abdominal",
    "Ninguno",
  ],
  ["Un día", "2 - 7 días", "Más de una semana", "Más de un mes"],
  [
    "Varias veces al día",
    "Una vez al día",
    "2 - 4 veces a la semana",
    "Una vez a la semana",
    "Varias veces al mes",
    "Una vez al mes",
  ],
  [
    "Anticoagulantes",
    "Analgésicos",
    "Antidepresivos",
    "Antihipertensivos",
    "Antidiabéticos",
    "Estatinas",
    "Ninguno",
    "Otros",
  ],
  ["Si", "No"],
  ["No aplica"],
  ["No aplica"],
  ["Si", "No"],
  ["Químico", "Biológico", "No aplica", "Otro"],
  ["Si", "No"],
  ["No aplica"],
  ["Decaido", "Cansado", "Ansioso", "Normal", "Falta de apetito", "Otros"],
];
